[pytest]
norecursedirs = venv .venv env Scripts Lib site-packages
python_files = test_*.py *_test.py
# addopts = --headed
addopts = --html=report.html --self-contained-html

markers =
    smoke: critical smoke tests marks tests as smoke ##(deselect with '-m \"not smoke\"')"
    regression: full regression suite
    api: API-only tests
    vrl: VRL smoke tests